server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&useSSL=false
    username: root
    password: qinliang
    #    username: ${ZENITH_USER:khyxcms_test}
    #    password: ${ZENITH_PASS:khyxcms_test@123}
    #    username: ${ZENITH_USER:khyxcms_dj}
    #    password: ${ZENITH_PASS:khyxcms_dj@123}
    #username: ${ZENITH_USER:ccpqry}
    #password: ${ZENITH_PASS:ccpqry@123}
    # connectionProperties: config.decrypt=false;config.decrypt.key=${PUBLICKEY:MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMUmMdZa3y+CEeURak8mjtLD26y7ssP99cigTuyt0Y+9krXf/+5mDPGx35RLZzNBzkphGBnV8VfuoOkdX9bmarcCAwEAAQ==}
    hikari:
      validation-timeout: 3000
      minimum-idle: 10    #池中维护的最小空闲连接数
      maximum-pool-size: 30  #池中最大连接数，包括闲置和使用中的连接
      auto-commit: true   #自动提交从池中返回的连接
      connection-timeout: 30000  #等待连接池分配连接的最大时长（毫秒），默认30秒
      idle-timeout: 600000  #连接允许在池中闲置的最长时间，默认10分钟
      max-lifetime: 1800000  #池中连接最长生命周期，默认30分钟
    driver-class-name: com.mysql.jdbc.Driver